## boot api ##

### findAll
GET http://localhost:8080/api/findAll

### insert
POST http://localhost:8080/api/insert
Content-Type: application/json

{
  "id": 4,
  "name": "phone charger",
  "description": "good phone charger",
  "quantity": 1,
  "price": 1500.00
}

### matchAll
GET http://localhost:8080/api/matchAll

### matchAllProducts
GET http://localhost:8080/api/matchAllProducts

### matchAllProductsWithFiledName
GET http://localhost:8080/api/matchAllProducts/mobile

### boolWithNameAndPriceRange
GET http://localhost:8080/api/bool?fieldValue=charger&lt=5000&gt=900